services:
  image-service:
    build: .
    container_name: image-service
    ports:
      # Map host port 4000 to container port 8080
      - "6000:8080"
    volumes:
      # Persist images on the host at /home/ubuntu/images
      - /var/www/project/auk/project/images:/app/static/images